# read the raw YouTube data files for 2007 and 2008 and save as txt files in 'data/' folder in container
# file names: "data2007_not_cleaned.txt" , "data2008_not_cleaned.txt"
load: /home/rstudio/R/load.R
	Rscript /home/rstudio/R/load.R "/home/rstudio/data/0007.txt" "/home/rstudio/data/0107.txt" "/home/rstudio/data/0207.txt" "/home/rstudio/data/0307.txt" "/home/rstudio/data/0008.txt" "/home/rstudio/data/0108.txt" "/home/rstudio/data/0208.txt" "/home/rstudio/data/0308.txt" "/home/rstudio/data/data2007_not_cleaned.txt" "/home/rstudio/data/data2008_not_cleaned.txt"

# remove unnecessary columns and converts category variable as factor class
# save the cleaned data sets as txt files in 'data/' folder in container
# file names: "data2007_cleaned.txt" "data2008_cleaned.txt"
tidy: /home/rstudio/R/tidy.R
	Rscript /home/rstudio/R/tidy.R "/home/rstudio/data/data2007_not_cleaned.txt" "/home/rstudio/data/data2008_not_cleaned.txt" "/home/rstudio/data/data2007_cleaned.txt" "/home/rstudio/data/data2008_cleaned.txt"

# create four figures used in the report and save as .png files
# files are saved in the folder 'output/' in container
figures: /home/rstudio/R/figures.R
	Rscript /home/rstudio/R/figures.R "/home/rstudio/data/data2007_cleaned.txt" "/home/rstudio/data/data2008_cleaned.txt" "/home/rstudio/output/"

# Loads in tidy data and generates the tables for the preliminary analysis and analysis section
# results are saved as .csv file in the folder 'output/' in container	
models: /home/rstudio/R/analysis.R
	Rscript /home/rstudio/R/analysis.R "/home/rstudio/data/data2007_cleaned.txt" "/home/rstudio/data/data2008_cleaned.txt" "/home/rstudio/output/"

# renders the report into a .html file 
# the report is in the folder 'analysis/' in container	
render: /home/rstudio/analysis/analysis.Rmd
	Rscript -e "rmarkdown::render(input = '/home/rstudio/analysis/analysis.Rmd',output_format = 'html_document', output_dir = '/home/rstudio/analysis/', encoding = 'UTF-8')"

# generate the report, all the figures, tables and data files:
.PHONY: all
all:
	make load
	make tidy
	make figures
	make models
	make render

# delete all files and folders generated by make all
.PHONY: clean
clean:
	rm -f /home/rstudio/data/data2007_not_cleaned.txt /home/rstudio/data/data2008_not_cleaned.txt
	rm -f /home/rstudio/data/data2007_cleaned.txt /home/rstudio/data/data2008_cleaned.txt
	rm -f /home/rstudio/output/*.png
	rm -f /home/rstudio/output/*.csv
	rm -f /home/rstudio/analysis/*.html
	rm -f *.html
	rm -f -d /home/rstudio/output/
